package formatter.data_manipulation.finder;

public enum FinderProperties {
	ID_EQUALS, 
	NAME_EQUALS, NAME_STARTS_WITH, NAME_ENDS_WITH, 
	CONTAINS_ATTRIBUTE_KEY, CONTAINS_ATTRIBUTE_VALUE,
	CONTAINS_CHILD_KEY, CONTAINS_CHILD_KEY_WITH_ATTRIBUTE_VALUE
}
